# Site settings
title: Electric Thread
email: evan@electricthread.com

# Exclude directories and/or files from the conversion.
# Grunt moves image files and the styles/scripts directories.
exclude: ['node_modules']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Build settings
markdown: kramdown
